version: '2'
services:
  fullcalendar-app:
    image: fullcalendar
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fullcalendar-postgresql:5432/fullCalendar
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://fullcalendar-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://fullcalendar-elasticsearch:9200
    ports:
      - 8080:8080
  fullcalendar-postgresql:
    extends:
      file: postgresql.yml
      service: fullcalendar-postgresql
  fullcalendar-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: fullcalendar-elasticsearch
